server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:6969/postgres
    password: password
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  logging:
    level:
      org:
        hibernate:
          SQL=DEBUG

